#line 1 "/Users/matt/dev/newt64.github/build/newt.l.c"

#line 3 "/Users/matt/dev/newt64.github/build/newt.l.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (yy_size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[223] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   20,   20,
        0,    0,    2,    2,    7,    7,   58,   53,   25,   24,
       24,   37,   53,   30,   29,   28,   53,   29,   49,   49,
       53,   53,   32,   32,   32,   53,   38,   38,   53,   25,
       53,   15,   15,   14,   14,   15,   56,   55,   55,   56,
       17,   17,   18,   57,   19,   19,   20,   21,   57,   23,
       22,    5,    2,    4,    4,    5,   10,    7,    9,    9,
        8,   25,   24,    0,   36,    0,   45,    0,   30,    0,
        0,   12,    0,    0,   51,   49,    0,   34,   35,    0,
        0,    0,   16,   31,   32,   46,   47,    0,   38,   38,

        0,    0,   39,   25,    0,    0,    0,    0,   14,   13,
       55,    0,   17,   19,   20,    0,   20,   22,    2,    4,
        0,    3,    7,    9,    8,    0,   41,    0,    0,    0,
       33,    0,   40,    0,    0,   11,    0,   40,    0,    0,
       51,    0,   50,    0,    0,   47,    0,    0,   48,   38,
       38,    0,    0,    0,   54,    0,    0,    0,    0,   42,
        0,    0,    0,    0,    0,   40,    0,    0,    0,    0,
        0,   51,    0,   38,   38,    0,    0,    0,    0,    0,
        0,   40,    0,    0,    0,    0,    0,    0,   52,   38,
       38,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   38,   38,    0,    6,   20,    0,   44,   43,    0,
        0,    0,   38,   38,    0,    0,    0,   26,   27,    0,
        1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    3,    4,
        1,    1,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,   10,   11,   12,   11,   11,
       11,   13,   14,   11,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   27,   27,   28,   29,
       30,   30,   31,   30,   30,   32,   30,   33,   30,   30,
       30,   30,   34,   30,   30,   30,   30,   30,   30,   30,
       11,   35,   11,   11,   36,   11,   27,   27,   37,   38,

       39,   27,   30,   30,   40,   30,   30,   41,   30,   42,
       30,   30,   30,   43,   44,   43,   45,   30,   30,   46,
       30,   30,   11,   47,   48,   11,   48,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    2,    1,    1,    1,    3,    3,    4,    3,    3,
        3,    3,    5,    3,    3,    3,    6,    7,    7,    3,
        3,    5,    3,    5,    3,    3,    8,    8,    8,    9,
        9,    9,    9,    9,   10,   11,    8,    8,    8,    9,
        9,    9,    9,    9,    9,    9,   12,    5,   13
    } ;

static const flex_int16_t yy_base[265] =
    {   0,
        0,   47,   54,   58,   47,   61,   50,   72,   81,   89,
      121,  164,   95,  101,  108,  114,  454,  815,   66,  815,
      449,   60,  417,  435,  815,  815,  430,  121,  123,  112,
       85,  172,  113,  422,   56,  125,    0,  408,  110,  176,
      177,  815,  815,  815,  439,  425,  815,  815,  428,  424,
      815,  421,   64,  815,  815,  420,  388,  815,  204,  815,
        0,  815,  167,  815,  418,  412,  815,  168,  815,  410,
      128,  178,  815,   94,  815,  208,  815,  246,  815,  396,
      196,  815,  407,  224,  196,  170,    0,  815,  815,  273,
      289,  158,  815,  815,  815,  201,    0,  187,    0,  194,

      193,  195,  815,  249,  230,  293,  368,  369,  815,  815,
      815,  400,  815,  815,  368,  294,  367,    0,  242,  815,
      393,  815,  254,  815,  219,  221,  815,    0,    0,    0,
      815,  227,  251,  305,  396,  815,  263,  265,  310,  339,
      286,  288,    0,  356,  253,    0,  273,  274,  815,  363,
      362,  355,  348,  383,  815,    0,  341,    0,  340,  815,
        0,    0,  306,  307,  309,  314,  346,  378,  400,  391,
      297,  346,  233,  351,  349,  339,  340,    0,    0,    0,
        0,  815,    0,  293,  422,  413,  444,    0,  815,  302,
      291,  265,  329,    0,    0,    0,    0,    0,  466,    0,

      488,  191,  151,  102,  340,   88,  363,  815,  815,    0,
      510,    0,   85,   79,   34,  334,    0,    0,    0,  367,
      369,  815,  549,  562,  575,  588,  601,  614,  625,  636,
      649,  656,  662,  671,  681,  687,  695,  706,  719,  726,
      728,  737,  749,  756,  763,  767,  769,  771,  773,  775,
      777,  779,  782,  786,  788,  790,  792,  794,  796,  798,
      800,  802,  804,  806
    } ;

static const flex_int16_t yy_def[265] =
    {   0,
      222,    1,  223,  223,  224,  224,    1,    1,  225,  225,
      226,  226,  227,  227,  228,  228,  222,  222,  222,  222,
      222,  229,  230,  222,  222,  222,  222,  231,  222,  222,
      222,  222,  222,  222,  222,  232,  233,  233,  234,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  235,  222,  222,  222,
      236,  222,  222,  222,  222,  237,  222,  222,  222,  222,
      222,  222,  222,  229,  222,  222,  222,  222,  222,  222,
      238,  222,  239,  238,  222,  222,  240,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  241,  242,  233,  233,

      234,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  243,  222,  222,  235,  222,  244,  236,  222,  222,
      237,  222,  222,  222,  222,  245,  222,  246,  247,  248,
      222,  238,  238,  222,  239,  222,  238,  238,  238,  238,
      222,  222,  240,  222,  222,  241,  242,  222,  222,  233,
      233,  222,  222,  243,  222,  249,  222,  250,  222,  222,
      251,  252,  238,  253,  238,  238,  238,  140,  140,  222,
      222,  222,  222,  233,  233,  222,  222,  254,  255,  256,
      257,  222,  258,  222,  169,  222,  169,  168,  222,  233,
      233,  222,  222,  259,  260,  261,  262,  263,  169,  168,

      169,  233,  233,  222,  222,  244,  245,  222,  222,  264,
      169,  140,  233,  233,  222,  253,  168,  233,  233,  222,
      222,    0,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222
    } ;

static const flex_int16_t yy_nxt[865] =
    {   0,
       18,   18,   19,   20,   21,   19,   18,   22,   18,   23,
       18,   24,   25,   26,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   18,   36,   37,   37,   37,   37,
       37,   37,   37,   37,   18,   38,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   39,   18,   18,   40,
       48,   49,   40,   51,   52,   41,   43,   44,   45,   43,
       43,   44,   45,   43,   48,   49,   46,   75,   72,   50,
       46,   72,  220,   53,   40,   51,   52,   40,   95,   94,
       41,   54,   54,   54,   55,   56,   95,   94,   58,   54,
       54,   54,   55,   56,   76,   53,   58,   63,   64,   65,

       63,   75,   66,   63,   64,   65,   63,   88,   66,   89,
       68,   69,   70,   68,  219,   59,   68,   69,   70,   68,
      218,   93,  157,   59,   54,   71,   71,   85,   76,   86,
       86,   71,   71,   82,   94,   95,   95,   83,   85,  215,
       86,   86,   96,   96,  102,  125,  125,   61,   61,   61,
       61,   61,   61,   61,   61,   84,  103,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   54,   87,  119,
      123,   98,  119,  123,   90,   90,   91,   90,  104,  106,
       72,  104,  106,   72,  105,   85,  214,   86,   86,  145,
       61,   61,   61,   61,   61,   61,   61,   61,  145,   92,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       92,  115,  133,  141,  141,   74,  107,  108,   96,   96,
      115,  148,  150,  142,   74,  151,  213,  102,   75,  101,
      134,  137,  106,  149,  142,  106,  125,  125,  115,  103,
      138,  101,   74,  133,  119,  115,  115,  119,  117,   74,
       74,  104,  126,  127,  104,  159,  123,  105,  139,  123,
      189,  134,  127,  128,  128,  137,  137,  133,  140,  107,
      108,  189,  128,  128,  128,   90,   90,   91,   90,  133,
      127,  133,  128,  128,  128,  134,  173,  127,  127,  129,
      130,   90,  144,   91,   90,  106,  173,  134,  106,  134,

       92,  115,  171,  141,  141,  172,  172,  148,  147,  204,
      115,   92,  163,  142,  172,  172,   92,  165,  203,  149,
      147,  163,  133,  182,  142,  133,  166,   92,  115,  202,
      133,  205,  107,  108,  205,  115,  115,  163,  117,  163,
      134,  184,  205,  134,  167,  205,  163,  163,  134,  164,
      182,  165,  165,  165,  168,  133,  169,  169,   90,   90,
       91,   90,  166,  172,  172,  169,  169,  169,  184,  221,
       75,  221,  221,  170,  221,  169,  169,  169,  193,  192,
      167,  191,  190,   92,   74,  115,  155,  165,  165,  177,
      168,  176,  175,  174,   92,  185,  185,  159,  163,  136,

      122,  157,  116,  155,  185,  185,  185,  163,  153,  152,
      136,  131,  186,  124,  185,  185,  185,  187,  187,  122,
      163,  120,  116,  114,  113,  163,  187,  187,  187,  163,
      112,  111,  163,  163,  134,  188,  187,  187,  187,  199,
      199,  110,  109,  100,   95,   80,   79,  163,  199,  199,
      199,   78,   73,  222,  163,  163,  222,  200,  199,  199,
      199,  201,  201,  222,  222,  222,  222,  222,  222,  222,
      201,  201,  201,  222,  222,  222,  222,  222,  222,  222,
      201,  201,  201,  211,  211,  222,  222,  222,  222,  222,
      222,  222,  211,  211,  211,  222,  222,  222,  222,  222,

      222,  222,  211,  211,  211,  212,  212,  222,  222,  222,
      222,  222,  222,  222,  212,  212,  212,  222,  222,  222,
      222,  222,  222,  222,  212,  212,  212,  217,  217,  222,
      222,  222,  222,  222,  222,  222,  217,  217,  217,  222,
      222,  222,  222,  222,  222,  222,  217,  217,  217,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,

       60,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   97,   97,   97,  222,   97,   97,   99,   99,
       99,  222,   99,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  115,  222,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  118,  118,  121,  121,  121,  222,

      121,  121,  121,  121,  121,  121,  222,  121,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  143,  143,  146,  146,  146,  222,  146,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  156,  156,  222,  156,  158,  222,  222,  158,
      158,  222,  158,  160,  160,  161,  161,  162,  162,  178,
      178,  179,  179,  180,  180,  181,  181,  183,  183,  183,
      222,  183,  194,  194,  195,  195,  196,  196,  197,  197,

      198,  198,  206,  206,  207,  207,  208,  208,  209,  209,
      210,  210,  216,  216,   17,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222
    } ;

static const flex_int16_t yy_chk[865] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        5,    5,    2,    7,    7,    2,    3,    3,    3,    3,
        4,    4,    4,    4,    6,    6,    3,   22,   19,    6,
        4,   19,  215,    7,    8,    8,    8,    8,   35,   35,
        8,    9,    9,    9,    9,    9,   53,   53,    9,   10,
       10,   10,   10,   10,   22,    8,   10,   13,   13,   13,

       13,   74,   13,   14,   14,   14,   14,   31,   14,   31,
       15,   15,   15,   15,  214,    9,   16,   16,   16,   16,
      213,   33,  206,   10,   11,   15,   15,   30,   74,   30,
       30,   16,   16,   28,   33,   33,   33,   28,   29,  204,
       29,   29,   36,   36,   39,   71,   71,   11,   11,   11,
       11,   11,   11,   11,   11,   28,   39,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,   29,   63,
       68,   36,   63,   68,   32,   32,   32,   32,   40,   41,
       72,   40,   41,   72,   40,   86,  203,   86,   86,   92,
       12,   12,   12,   12,   12,   12,   12,   12,   92,   32,

       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       32,   59,   81,   85,   85,   76,   41,   41,   96,   96,
       59,   98,  100,   85,   76,  100,  202,  101,  126,  102,
       81,   84,  105,   98,   85,  105,  125,  125,   59,  101,
       84,  102,   76,  132,  119,   59,   59,  119,   59,   76,
       76,  104,   76,   78,  104,  126,  123,  104,   84,  123,
      173,  132,   78,   78,   78,   84,   84,  133,   84,  105,
      105,  173,   78,   78,   78,   90,   90,   90,   90,  137,
       78,  138,   78,   78,   78,  133,  145,   78,   78,   78,
       78,   91,   91,   91,   91,  106,  145,  137,  106,  138,

       90,  116,  142,  141,  141,  142,  142,  147,  148,  192,
      116,   90,  134,  141,  171,  171,   91,  139,  191,  147,
      148,  134,  163,  164,  141,  165,  139,   91,  116,  190,
      166,  193,  106,  106,  193,  116,  116,  184,  116,  134,
      163,  164,  205,  165,  139,  205,  134,  134,  166,  134,
      216,  139,  139,  167,  139,  140,  140,  140,  144,  144,
      144,  144,  167,  172,  172,  140,  140,  140,  216,  220,
      207,  221,  220,  140,  221,  140,  140,  140,  177,  176,
      167,  175,  174,  144,  159,  157,  154,  167,  167,  153,
      167,  152,  151,  150,  144,  168,  168,  207,  170,  135,

      121,  117,  115,  112,  168,  168,  168,  170,  108,  107,
       83,   80,  168,   70,  168,  168,  168,  169,  169,   66,
      186,   65,   57,   56,   52,  170,  169,  169,  169,  186,
       50,   49,  170,  170,  169,  170,  169,  169,  169,  185,
      185,   46,   45,   38,   34,   27,   24,  186,  185,  185,
      185,   23,   21,   17,  186,  186,    0,  186,  185,  185,
      185,  187,  187,    0,    0,    0,    0,    0,    0,    0,
      187,  187,  187,    0,    0,    0,    0,    0,    0,    0,
      187,  187,  187,  199,  199,    0,    0,    0,    0,    0,
        0,    0,  199,  199,  199,    0,    0,    0,    0,    0,

        0,    0,  199,  199,  199,  201,  201,    0,    0,    0,
        0,    0,    0,    0,  201,  201,  201,    0,    0,    0,
        0,    0,    0,    0,  201,  201,  201,  211,  211,    0,
        0,    0,    0,    0,    0,    0,  211,  211,  211,    0,
        0,    0,    0,    0,    0,    0,  211,  211,  211,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,

      226,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  232,  232,  232,    0,  232,  232,  233,  233,
      233,    0,  233,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  235,    0,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  236,  236,  237,  237,  237,    0,

      237,  237,  237,  237,  237,  237,    0,  237,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  240,  240,  241,  241,  241,    0,  241,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  244,  244,    0,  244,  245,    0,    0,  245,
      245,    0,  245,  246,  246,  247,  247,  248,  248,  249,
      249,  250,  250,  251,  251,  252,  252,  253,  253,  253,
        0,  253,  254,  254,  255,  255,  256,  256,  257,  257,

      258,  258,  259,  259,  260,  260,  261,  261,  262,  262,
      263,  263,  264,  264,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/parser/newt.l"
/*------------------------------------------------------------------------*/
/**
 * @file	newt.l
 * @brief   字句解析
 *
 * @author  M.Nukui
 * @date	2003-11-07
 *
 * Copyright (C) 2003-2004 M.Nukui All rights reserved.
 */
/*
%option interactive
*/
#line 20 "src/parser/newt.l"

/* ヘッダファイル */
#include <string.h>

#include "NewtErrs.h"
#include "NewtObj.h"
#include "NewtEnv.h"
#include "NewtParser.h"
#include "NewtPrint.h"
#include "NewtIO.h"

#include "lookup_words.h"
#include "yacc.h"
#include "y.tab.h"


/* 関数プロトタイプ */
static int			lex_update_tokenpos(int op);
static void			lex_newline(void);

static char *		lex_truncstr(char *s);
static char *		lex_escapestr(char *s);
static char			lex_escapechar(char c);
static int          lex_htoi(char *s, int len);
static uint64_t     lex_htoll(char *s, int len);
static uint32_t		lex_getop(char *s);
static int			lex_op(char *s, int op);
static int			lex_reserveword(int tokn, char *s);

static int			lex_makesymbol(char *s, bool trunc);
static int			lex_makestring(char *s, bool trunc);
static int			lex_makeregex(char *s, bool trunc);
static int          lex_makechar(int c);
static int          lex_makespecial(int c);
static int			lex_makeinteger(int64_t n);
static int			lex_makereal(double n);

static int			lex_makemagicpointer(int n);
static int			lex_makenamedmp(char *s, bool trunc);

static int          lex_include_file(char *s);
static void         lex_include_invalid_filename(void);
static int          lex_include_done(void);

static int          lex_set_line(char *s);
static void         lex_invalid_line(void);

static void			lex_debug(int type);

#define MAX_INCLUDE_DEPTH 10
YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
int include_stack_ptr = 0;

/* マクロ */
#undef YY_INPUT
#define YY_INPUT(b, r, ms) (r=nps_yyinput(yyin, b, ms))

#define WORN_NOS2(msg)		if (NEWT_MODE_NOS2) NPSErrorStr('W', msg);

#line 793 "/Users/matt/dev/newt64.github/build/newt.l.c"

#line 795 "/Users/matt/dev/newt64.github/build/newt.l.c"

#define INITIAL 0
#define COMMENT 1
#define SHELL 2
#define BINARY 3
#define STRING 4
#define REGEX 5
#define INCL 6
#define LINE 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 113 "src/parser/newt.l"



#line 117 "src/parser/newt.l"
    if (nps_env.first_time)
    {   //初回起動時
        nps_env.first_time = false;
        BEGIN SHELL;
    }


                                /* allow "C" style including of more script files */
#line 1035 "/Users/matt/dev/newt64.github/build/newt.l.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 223 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 815 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 125 "src/parser/newt.l"
{ BEGIN INCL; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 126 "src/parser/newt.l"
/* eat the whitespace */
	YY_BREAK
/* read the file name in double quotes */
case 3:
YY_RULE_SETUP
#line 128 "src/parser/newt.l"
lex_include_file(yytext);
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 129 "src/parser/newt.l"
lex_include_invalid_filename();
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 130 "src/parser/newt.l"
lex_include_invalid_filename();
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(SHELL):
case YY_STATE_EOF(BINARY):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(REGEX):
case YY_STATE_EOF(INCL):
case YY_STATE_EOF(LINE):
#line 131 "src/parser/newt.l"
if (lex_include_done()==0) return 0;
	YY_BREAK
/* allow '#line n' to change current line number */
case 6:
YY_RULE_SETUP
#line 134 "src/parser/newt.l"
{ BEGIN LINE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 135 "src/parser/newt.l"
/* eat the whitespace */
	YY_BREAK
/* read the line number */
case 8:
YY_RULE_SETUP
#line 137 "src/parser/newt.l"
lex_set_line(yytext);
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 138 "src/parser/newt.l"
lex_invalid_line();
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 139 "src/parser/newt.l"
lex_invalid_line();
	YY_BREAK
case 11:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 142 "src/parser/newt.l"

	YY_BREAK
case 12:
YY_RULE_SETUP
#line 144 "src/parser/newt.l"
{
									BEGIN COMMENT;
									lex_update_tokenpos(0);
								}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 149 "src/parser/newt.l"
{
									BEGIN INITIAL;
									lex_update_tokenpos(0);
								}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 154 "src/parser/newt.l"
lex_newline();
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 155 "src/parser/newt.l"
lex_update_tokenpos(0);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 157 "src/parser/newt.l"
{
									BEGIN BINARY;
									return lex_update_tokenpos(kBINBG);
								}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 162 "src/parser/newt.l"
lex_newline();
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 163 "src/parser/newt.l"
{
									BEGIN INITIAL;
									return lex_update_tokenpos(kBINED);
								}
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 168 "src/parser/newt.l"
{
									nps_env.lineno++;
									yymore();
								}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 173 "src/parser/newt.l"
yymore();
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 174 "src/parser/newt.l"
{
									BEGIN INITIAL;
									return lex_makestring(yytext, true);
								}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 179 "src/parser/newt.l"
{ return lex_makestring(yytext, false); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 180 "src/parser/newt.l"
{
									unput(*yytext);
									BEGIN INITIAL;
								}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 185 "src/parser/newt.l"
lex_newline();
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 186 "src/parser/newt.l"
lex_update_tokenpos(0);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 188 "src/parser/newt.l"
{ return lex_makestring((char *)(nps_env.fname?nps_env.fname:"-"), false); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 189 "src/parser/newt.l"
{ return lex_makeinteger(nps_env.lineno); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 191 "src/parser/newt.l"
{ return lex_op(yytext, kADDOP); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 192 "src/parser/newt.l"
{ return lex_op(yytext, kMULOP); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 193 "src/parser/newt.l"
{ return lex_op(yytext, kSTROP); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 194 "src/parser/newt.l"
{ return lex_op(yytext, kSFTOP); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 195 "src/parser/newt.l"
{ return lex_op(yytext, kRELOP); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 196 "src/parser/newt.l"
{ return lex_update_tokenpos(k3READER); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 198 "src/parser/newt.l"
{ return lex_update_tokenpos(kASNOP); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 199 "src/parser/newt.l"
{ return lex_update_tokenpos(kSNDOP); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 201 "src/parser/newt.l"
{ return lex_makestring(yytext, true); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 203 "src/parser/newt.l"
{
									BEGIN STRING;
									yymore();
								}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 208 "src/parser/newt.l"
{ return lex_makesymbol(yytext, false); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 209 "src/parser/newt.l"
{ return lex_makesymbol(yytext, true); }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 211 "src/parser/newt.l"
{
									BEGIN REGEX;
									return lex_makeregex(yytext, true);
								}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 216 "src/parser/newt.l"
{ return lex_makechar(lex_escapechar(yytext[2])); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 217 "src/parser/newt.l"
{ return lex_makechar(lex_htoi(yytext + 2, -1)); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 218 "src/parser/newt.l"
{ return lex_makechar(lex_htoi(yytext + 3, -1)); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 219 "src/parser/newt.l"
{ return lex_makespecial(lex_htoi(yytext + 3, -1)); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 220 "src/parser/newt.l"
{ return lex_makechar(yytext[1]); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 222 "src/parser/newt.l"
{ return lex_makemagicpointer(atoi(yytext + 1)); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 223 "src/parser/newt.l"
{ return lex_makenamedmp(yytext + 1, false); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 224 "src/parser/newt.l"
{ return lex_makenamedmp(yytext + 1, true); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 226 "src/parser/newt.l"
{ return lex_makeinteger(atoll(yytext)); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 227 "src/parser/newt.l"
{ return lex_makeinteger(lex_htoll(yytext + 2, -1)); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 229 "src/parser/newt.l"
{ return lex_makereal(atof(yytext)); }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 231 "src/parser/newt.l"
{ return lex_update_tokenpos(kELSE); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 233 "src/parser/newt.l"
{ return lex_update_tokenpos(yytext[0]); }
	YY_BREAK
/* if the very first line starts witha "shebang" (#!),
                                 * Unix shells will run the tool indicated following the #! */
/* if the line starts with #!, ignore the entire line, then start parsing */
case 54:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 238 "src/parser/newt.l"
{ BEGIN INITIAL; }
	YY_BREAK
/* if the line is empty, count it and start parsing */
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 240 "src/parser/newt.l"
{ lex_newline(); BEGIN INITIAL; }
	YY_BREAK
/* any other character on the input line will unread it and start parsing */
case 56:
YY_RULE_SETUP
#line 242 "src/parser/newt.l"
{ unput(*yytext); BEGIN INITIAL; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 244 "src/parser/newt.l"
ECHO;
	YY_BREAK
#line 1445 "/Users/matt/dev/newt64.github/build/newt.l.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 223 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 223 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 222);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 244 "src/parser/newt.l"



/// 一部の lex で YY_FLUSH_BUFFER が undef されてしまう問題に対応
#ifndef YY_FLUSH_BUFFER
	#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )
#endif


/// 予約語
static keyword_t	reserved_words[] = {
		// アルファベット順にソートしておくこと
		{"AND",			kANDOP},		// 予約語
        {"BEGIN",		kBEGIN},		// 予約語
        {"BREAK",		kBREAK},		// 予約語
        {"BY",			kBY},			// 予約語
        {"CALL",		kCALL},			// 予約語
//		{"COLLECT",		kCOLLECT},
        {"CONSTANT",	kCONSTANT},		// 予約語
//		{"DEEPLY",		kDEEPLY},
        {"DIV",			kMULOP},		// 予約語
        {"DO",			kDO},			// 予約語
        {"ELSE",		kELSE},			// 予約語
        {"END",			kEND},			// 予約語
        {"EXISTS",		kEXISTS},		// 予約語
        {"FOR",			kFOR},			// 予約語
        {"FOREACH",		kFOREACH},		// 予約語
        {"FUNC",		kFUNC},			// 予約語
        {"GLOBAL",		kGLOBAL},		// 予約語
        {"IF",			kIF},			// 予約語
        {"IN",			kIN},			// 予約語
        {"INHERITED",	kINHERITED},	// 予約語
        {"LOCAL",		kLOCAL},		// 予約語
        {"LOOP",		kLOOP},			// 予約語
        {"MOD",			kMULOP},		// 予約語
        {"NATIVE",		kNATIVE},		// 予約語
        {"NIL",			kNIL},
        {"NOT",			kNOTOP},		// 予約語
        {"ONEXCEPTION",	kONEXCEPTION},	// 予約語
        {"OR",			kOROP},			// 予約語
        {"REPEAT",		kREPEAT},		// 予約語
        {"RETURN",		kRETURN},		// 予約語
        {"SELF",		kSELF},			// 予約語
        {"THEN",		kTHEN},			// 予約語
        {"TO",			kTO},			// 予約語
        {"TRUE",		kTRUE},
        {"TRY",			kTRY},			// 予約語
        {"UNTIL",		kUNTIL},		// 予約語
        {"WHILE",		kWHILE},		// 予約語
        {"WITH",		kWITH},			// 予約語
    };

/// オペレータ
static keyword_t	operator_words[] = {
		// アルファベット順にソートしておくこと
        {"&&",			kNPS_CONCAT2},
        {"<<",			kNPS_SHIFT_LEFT},
        {"<=",			kNPS_LESS_EQUAL},
        {"<>",			kNPS_NOT_EQUAL},
        {"==",			kNPS_OBJECT_EQUAL},
        {">=",			kNPS_GREATER_EQUAL},
        {">>",			kNPS_SHIFT_RIGHT},
	};


/*------------------------------------------------------------------------*/
/** トークンの位置を更新
 *
 * @param op		[in] オペレータ
 *
 * @return			オペレータをそのまま返す
 */

int lex_update_tokenpos(int op)
{
	strncat(nps_env.linebuf, yytext, sizeof(nps_env.linebuf));

	nps_env.tokenpos += yyleng;
	nps_env.yyleng = yyleng;
	return op;
}


/*------------------------------------------------------------------------*/
/** 新しい行の初期化
 *
 * @return			なし
 *
 * @note			エラー箇所を適切に表示するために入力行を保持する
 */

void lex_newline(void)
{
	uint32_t	n = 1;

	if (yytext[0] == '\r' && yytext[1] == '\n')
		n++;

	nps_env.linebuf[0] = '\0';
	nps_env.tokenpos = 0;
	nps_env.yyleng = 0;
	nps_env.lineno++;
	yyless(n);
}


/*------------------------------------------------------------------------*/
/** 文字列の前後１文字を切り詰める
 *
 * @param s			[in] 文字列
 *
 * @return			切り詰めたられた文字列
 */

char * lex_truncstr(char *s)
{
    s[strlen(s) - 1] = '\0';

    return s + 1;
}


/*------------------------------------------------------------------------*/
/** エスケープされた文字列を処理する
 *
 * @param s			[in] エスケープされた文字列
 *
 * @return			文字列
 */

char * lex_escapestr(char *s)
{
    int		uni = 0;
    char *	src;
    char *	dst;

    dst = src = s;

    while (*src)
    {
        if (*src =='\\')
        {
            src++;

            if (*src == 'u')
            {
                uni = ! uni;
            }
            else
            {
              	*dst = lex_escapechar(*src);
                dst++;
            }

            src++;
        }
        else if (uni)
        {
/*
            *dst = lex_htoi(src, 4);
            src += 4;
            dst++;
*/
            *dst = lex_htoi(src, 2);
            src += 2;
            dst++;

            *dst = lex_htoi(src, 2);
            src += 2;
            dst++;
        }
        else
        {
            if (dst != src)
                *dst = *src;

            dst++;
            src++;
        }
    }

    *dst = '\0';

    return s;
}


/*------------------------------------------------------------------------*/
/** エスケープ文字を処理する
 *
 * @param c			[in] エスケープ文字
 *
 * @return			文字
 */

char lex_escapechar(char c)
{
    switch (c)
    {
        case 'n':
            c = '\n';
            break;

        case 'r':
            c = '\r';
            break;

        case 't':
            c = '\t';
            break;
    }

    return c;
}


/*------------------------------------------------------------------------*/
/** 16進数文字列を整数に変換
 *
 * @param s			[in] 16進数文字列
 * @param len		[in] 16進数文字列の長さ
 *
 * @return			整数
 */
int lex_htoi(char *s, int len)
{
    int	n = 0;

    if (len < 0)
        len = (int)strlen(s) + 1 + len;

    while (0 < len)
    {
        n *= 16;

        if ('A' <= *s && *s <= 'F')
            n += *s - 'A' + 10;
        else if ('a' <= *s && *s <= 'f')
            n += *s - 'a' + 10;
        else
            n += *s - '0';

        s++;
        len--;
    }

    return n;
}


/*------------------------------------------------------------------------*/
/** 64 bit version of reading a hexadecimal number
 */
uint64_t lex_htoll(char *s, int len)
{
    uint64_t n = 0;

    if (len < 0)
    len = (int)strlen(s) + 1 + len;

    while (0 < len)
    {
        n *= 16;

        if ('A' <= *s && *s <= 'F')
        n += *s - 'A' + 10;
        else if ('a' <= *s && *s <= 'f')
        n += *s - 'a' + 10;
        else
        n += *s - '0';

        s++;
        len--;
    }

    return n;
}


/*------------------------------------------------------------------------*/
/** オペレータ文字列からオペレータIDを求める
 *
 * @param s			[in] オペレータ文字列
 *
 * @return			オペレータID
 */

uint32_t lex_getop(char *s)
{
    uint32_t	op;
    int	len;

	len = (int)strlen(s);

    if (len == 1)
    {
        op = s[0];
    }
    else
    {
        int	wlen;

        wlen = sizeof(operator_words) / sizeof(keyword_t);
        op = lookup_words(operator_words, wlen, s);
    }

    return op;
}


/*------------------------------------------------------------------------*/
/** オペレータトークンの作成
 *
 * @param s			[in] オペレータ文字列
 *
 * @return			トークンID
 */

int lex_op(char *s, int op)
{
    yylval.op = lex_getop(yytext);
	return lex_update_tokenpos(op);
}


/*------------------------------------------------------------------------*/
/** 予約語のトークンを作成
 *
 * @param tokn		[in] トークンID
 * @param s			[in] オペレータ文字列
 *
 * @return			トークンID
 */

int lex_reserveword(int tokn, char *s)
{
    switch (tokn)
    {
        case kMULOP:
            if (strcasecmp(s, "div") == 0)
                yylval.op = kNPS_DIV;
            else if (strcasecmp(s, "mod") == 0)
                yylval.op = kNPS_MOD;
            break;

        case kNOTOP:
            yylval.op = kNPS_NOT;
            break;
    }

    return tokn;
}


/*------------------------------------------------------------------------*/
/** シンボルトークンの作成
 *
 * @param s			[in] 文字列
 * @param trunc		[in] 前後の切り詰め
 *
 * @return			トークンID
 */

int lex_makesymbol(char *s, bool trunc)
{
    if (trunc)
    {
        s = lex_escapestr(lex_truncstr(s));
    }
    else
    {
        int	tokn;
        int	wlen;

        wlen = sizeof(reserved_words) / sizeof(keyword_t);
        tokn = lookup_words(reserved_words, wlen, s);

        if (tokn != -1)
            return lex_update_tokenpos(lex_reserveword(tokn, s));
    }

    yylval.obj = NewtMakeSymbol(s);
    lex_debug(kSYMBOL);

	return lex_update_tokenpos(kSYMBOL);
}


/*------------------------------------------------------------------------*/
/** 文字列トークンの作成
 *
 * @param s			[in] 文字列
 * @param trunc		[in] 前後の切り詰め
 *
 * @return			トークンID
 */

int lex_makestring(char *s, bool trunc)
{
    if (trunc)
        s = lex_escapestr(lex_truncstr(s));

    yylval.obj = NewtMakeString(s, true);
    lex_debug(kSTRING);

	return lex_update_tokenpos(kSTRING);
}


/*------------------------------------------------------------------------*/
/** 正規表現トークンの作成
 *
 * @param s			[in] 文字列
 * @param trunc		[in] 前後の切り詰め
 *
 * @return			トークンID
 */

int lex_makeregex(char *s, bool trunc)
{
    if (trunc)
        s = lex_escapestr(lex_truncstr(s));

    yylval.obj = NewtMakeString(s, true);
    lex_debug(kREGEX);

	return lex_update_tokenpos(kREGEX);
}


/*------------------------------------------------------------------------*/
/** 文字トークンの作成
 *
 * @param c			[in] 文字
 *
 * @return			トークンID
 */

int lex_makechar(int c)
{
    yylval.obj = NewtMakeCharacter(c);
    lex_debug(kCHARACTER);

	return lex_update_tokenpos(kCHARACTER);
}


/*------------------------------------------------------------------------*/
/** Make a special code (this is similar to a character, and it is needed
 * as a function signature for newer .pkg files)
 *
 * @param c            [in] special value
 *
 * @return            Special Ref
 */

int lex_makespecial(int c)
{
    yylval.obj = NewtMakeSpecial(c);
    lex_debug(kSPECIAL);

    return lex_update_tokenpos(kSPECIAL);
}


/*------------------------------------------------------------------------*/
/** 整数トークンの作成
 *
 * @param n			[in] 整数
 *
 * @return			トークンID
 */

int lex_makeinteger(int64_t n)
{
    yylval.obj = NewtMakeInteger(n);
    lex_debug(kINTEGER);

	return lex_update_tokenpos(kINTEGER);
}


/*------------------------------------------------------------------------*/
/** 浮動小数点トークンの作成
 *
 * @param n			[in] 浮動小数点
 *
 * @return			トークンID
 */

int lex_makereal(double n)
{
    yylval.obj = NewtMakeReal(n);
    lex_debug(kREAL);

	return lex_update_tokenpos(kREAL);
}


#ifdef __NAMED_MAGIC_POINTER__

/*------------------------------------------------------------------------*/
/** 名前付マジックポインタの作成
 *
 * @param s			[in] 文字列
 * @param trunc		[in] 前後の切り詰め
 *
 * @return			トークンID
 */

int lex_makenamedmp(char *s, bool trunc)
{
	int		pos;

    if (trunc)
    {
        s = lex_escapestr(lex_truncstr(s));
    }

    yylval.obj = NewtMakeNamedMP(s);
    lex_debug(kMAGICPOINTER);

	pos = lex_update_tokenpos(kMAGICPOINTER);

	// NOS2 非互換
	WORN_NOS2("Named Magic Pointer");

	return pos;
}

#else

/*------------------------------------------------------------------------*/
/** 名前付マジックポインタの作成
 *
 * @param s			[in] 文字列
 * @param trunc		[in] 前後の切り詰め
 *
 * @return			トークンID
 */

int lex_makenamedmp(char *s, bool trunc)
{
	return lex_update_tokenpos(kERROR);
}

#endif


/*------------------------------------------------------------------------*/
/** マジックポインタトークンの作成
 *
 * @param n			[in] マジックポインタ番号
 *
 * @return			トークンID
 */

int lex_makemagicpointer(int n)
{
	if (0x03ff < n)
	{	// 数値が範囲外
		return lex_update_tokenpos(kERROR);
	}

	yylval.obj = NewtMakeMagicPointer(0, n);
    lex_debug(kMAGICPOINTER);

	return lex_update_tokenpos(kMAGICPOINTER);
}


#if 0
#pragma mark -
#endif
/*------------------------------------------------------------------------*/
/** デバッグ表示
 *
 * @param type		[in] トークンID
 *
 * @return			なし
 */

void lex_debug(int type)
{
    char *	name = "unknown";

    if (! NEWT_DUMPLEX)
        return;

    switch (type)
    {
        case kSYMBOL:
            name = "symbol";
            break;

        case kSTRING:
            name = "string";
            break;

        case kINTEGER:
            name = "integer";
            break;

        case kREAL:
            name = "real";
            break;

		case kMAGICPOINTER:
            name = "magic pointer";
			break;
    }

    NewtFprintf(stderr, "  %s\t==> ", name);
    NewtPrintObject(stderr, yylval.obj);
}

#if 0
#pragma mark -
#endif
//--------------------------------------------------------------------------
/**
 * Include a file into the source code.
 */
int lex_include_file(char *filename)
{
    filename++; filename[strlen(filename)-1]=0;
    if (include_stack_ptr>=MAX_INCLUDE_DEPTH) {
        NewtFprintf(stderr, "%s:%d: error: includes nested too deeply.\n",
            nps_env.fname?nps_env.fname:"-",
            nps_env.lineno);
        exit(1);
    }
    include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;
    yyin = fopen( filename, "rb" );
    if (!yyin) {
        NewtFprintf(stderr, "%s:%d: error: %s: %s\n%s\n",
            nps_env.fname?nps_env.fname:"-",
            nps_env.lineno,
            filename,
            strerror(errno));
        exit(1);
    }

    yy_switch_to_buffer(
        yy_create_buffer( yyin, YY_BUF_SIZE )
    );

    BEGIN INITIAL;
    return lex_update_tokenpos(0);
}

/**
 * If we could not read the filename, give an error message and terminate.
 * FIXME: this should unroll the include buffer and return gracefully.
 */
void lex_include_invalid_filename()
{
    NewtFprintf(stderr, "%s:%d: error: include: Invalid filename.\n%s\n",
        nps_env.fname?nps_env.fname:"-",
        nps_env.lineno,
        nps_env.linebuf);
    exit(1);
}

/**
 * We reached the end of the current file; unroll the include stack and terminate
 * if there are no more files.
 *
 * @return 0 if there are no more files on the stack and we should terminate
 */
int lex_include_done()
{
    if ( --include_stack_ptr < 0 )
        yyterminate(); // this macro returns 0!
    else
        yy_switch_to_buffer( include_stack[include_stack_ptr] );
    return 1;
}

#if 0
#pragma mark -
#endif
//--------------------------------------------------------------------------

int lex_set_line(char *s)
{
    nps_env.lineno = atoi(s);
    BEGIN INITIAL;
    return lex_update_tokenpos(0);
}

void lex_invalid_line(void)
{
    NewtFprintf(stderr, "%s:%d: error: line: Invalid format.\n%s\n",
    nps_env.fname?nps_env.fname:"-",
    nps_env.lineno,
    nps_env.linebuf);
    exit(1);
}

#if 0
#pragma mark -
#endif
//--------------------------------------------------------------------------
/** 字句解析のための初期化
 *
 * @return			なし
 */

void nps_yyinit(void)
{
	static bool inited = 0; // was "false"

	if (! inited)
	{   //単語テーブルのソート
		lookup_sorttable(reserved_words, sizeof(reserved_words) / sizeof(keyword_t));
		lookup_sorttable(operator_words, sizeof(operator_words) / sizeof(keyword_t));

		inited = true;
	}
}


//--------------------------------------------------------------------------
/** 字句解析の後始末
 *
 * @return			なし
 */

int nps_yycleanup(void)
{
	BEGIN INITIAL;
	YY_FLUSH_BUFFER;
    memset(nps_env.linebuf, '\0', sizeof(nps_env.linebuf));
	yyterminate();
}

