/* src/config.h.  Generated by configure.  */
/*------------------------------------------------------------------------*/
/**
 * @file	config.h
 * @brief   コンフィグ設定
 *
 * @author  M.Nukui
 * @date	2005-04-30
 *
 * Copyright (C) 2005 M.Nukui All rights reserved.
 */


#ifndef	CONFIG_H
#define	CONFIG_H


/* マクロ定義 */
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_MEMORY_H 1
/* #undef HAVE_UNISTD_H */
/* #undef HAVE_ENDIAN_H */
/* #undef HAVE_MACHINE_ENDIAN_H */
/* #undef HAVE_TERMIOS_H */

/* #undef HAVE_LIBICONV */
#define HAVE_DLOPEN 1
#define HAVE_MMAP 1
#define HAVE_CHDIR 1
#define HAVE_GETCWD 1
/* #undef HAVE_GETPWNAM */

#define __PLATFORM__ "win32"
#define __DYLIBSUFFIX__ ".dll"
#define __LIBDIR__ "%SystemRoot%\\system32\\"

/* #undef __IPOD__ */

#undef __IPOD__

#define strcasecmp stricmp
#define strncasecmp strnicmp
#define strcasestr StrStrI

#endif /* CONFIG_H */
